#
# Route Front 
#
index:
    path: /
    controller: App\Controller\FrontController::index

contact:
    path: /contact
    controller: App\Controller\FrontController::getContactForm
    methods:    [GET]

contactPost:
    path: /contact
    controller: App\Controller\FrontController::getContactPost
    methods:    [POST]


#
# Route Admin Panel
#
admin:
    path:    /admin
    controller: App\Controller\DietController::index

getView:
    path:    /admin/getView/{time}
    controller: App\Controller\AdminController::getView
    defaults:
        time: 'month'
login:
    path:    /login
    controller: App\Controller\AdminController::getIndex

app_logout:
    path: /logout


#
# Route Diet
#
getDiet:
    path:     /getDiet/{id}
    controller: App\Controller\DietController::getDiet

getListDiet:
    path:     /getListDiet/{id}/{newDiet}
    controller: App\Controller\DietController::getListDiet

addDiet:
    path:    /addDiet/{idAliment}/{quantity}/{repas}
    controller: App\Controller\DietController::addDiet

delDietItem:
    path:    /delDietItem/{id}
    controller: App\Controller\DietController::delDietItem

addClientForm:
    path:    /addClientForm
    controller: App\Controller\ClientController::addClientForm
    
addClient:
    path:    /addClient
    controller: App\Controller\ClientController::addClient


delDiet:
    path:    /delDiet/{idDiet}/{idClient}
    controller: App\Controller\DietController::delDiet

getDietExcel:
    path:    /getDietExcel/{idDiet}
    controller: App\Controller\ExportController::getDietExcel


#
# Route Api
#

getProduct:
    path:    /getProduct
    controller: App\Controller\ApiController::getProduct